### ISSUE TITLE
Android 10 Support 

### ISSUE THREAD

**Issue by modularanne** [ThePieMonster/HideMockLocation#29] opened 2022-03-21 10:12 UTC
As there is little documentation, I viewed manifest of the 2.0x releases and all seem to require 11 (sdk30). 

Any chance for android 10 compatibility or is it dependent on 11?

**Comment by ThePieMonster** [comment] 2022-03-21 17:08
@modularanne There is currently no plans for Android 10 as LSPosed was intended for Android 11 (but does support Android 8.1 ~ 13 DP1) now. If someone wishes to create a pull request  adding Android 10 support I would be happy to merge that in.

In addition, the documentation mentions the supported OS below on the first line.
>Hide Mock Location is an Xposed Module (now LSPosed on Android 11), which hides information about the 'Allow mock locations' setting.

**Comment by Albirew** [comment] 2022-07-20 15:47
On Android10, i use "Mock Mock Location" witch do pretty much the same.
if anything, i don't believe you should bother rewrite module since it already exist...

**Comment by irmo-de** [comment] 2023-01-11 11:03
@Albirew 
Where can I find  "Mock Mock Location"

**Comment by Albirew** [comment] 2023-01-11 17:50
apk: https://forum.xda-developers.com/t/mod-xposed-mockmocklocations-prevents-apps-from-detecting-allow-mock-locations.2910660/
git repo: https://github.com/bnalls33/MockMockLocations

module is old but still work on android 10 and 11.

**Comment by ThePieMonster** [comment] 2023-01-11 18:18
Thanks @Albirew for the information. I'll keep this open so others can find this.

**Comment by Albirew** [comment] 2023-01-11 18:25
you can also [pin the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) and close it, it will still appear on top of issues list even closed

**Closed as completed** 2023-01-11 18:35 UTC
Labels: documentation

**Comment by Imam7861** [comment] 2023-02-25 17:11
> On Android10, i use "Mock Mock Location" witch do pretty much the same. if anything, i don't believe you should bother rewrite module since it already exist...

Not working

**Comment by DeanWinchesterrr** [comment] 2023-12-22 11:37
> > On Android10, i use "Mock Mock Location" witch do pretty much the same. if anything, i don't believe you should bother rewrite module since it already exist...
> 
> Not working

Try this 

Git repo:
https://github.com/marlowww/HideMockLocation

Apk:
https://apkcombo.com/hide-mock-location/com.github.marlowww.hidemocklocation/

Working for me on Android 10
